data:extend(
{    
  {--prototype for object that gets stored in inventory when ore is mined
    type = "item",
    name = "automation-science-ore",
    icons = {{icon = "__leighzerscienceores__/graphics/icons/ore.png", tint= leighzermods.leighzerscienceores.tints.automation}},
    icon_size = 32,            
    subgroup = "raw-resource",
    order = "a-b-a",
    stack_size = 50,
  },
  {
    type = "item",
    name = "logistic-science-ore",
    icons = {{icon = "__leighzerscienceores__/graphics/icons/ore.png", tint= leighzermods.leighzerscienceores.tints.logistic}},
    icon_size = 32,            
    subgroup = "raw-resource",
    order = "a-b-a",
    stack_size = 50,
  },
  {
    type = "item",
    name = "military-science-ore",
    icons = {{icon = "__leighzerscienceores__/graphics/icons/ore.png", tint= leighzermods.leighzerscienceores.tints.military}},
    icon_size = 32,            
    subgroup = "raw-resource",
    order = "a-b-a",
    stack_size = 50,
  },
  {
    type = "item",
    name = "chemical-science-ore",
    icons = {{icon = "__leighzerscienceores__/graphics/icons/ore.png", tint= leighzermods.leighzerscienceores.tints.chemical}},
    icon_size = 32,            
    subgroup = "raw-resource",
    order = "a-b-a",
    stack_size = 50,
  },
  {
    type = "item",
    name = "production-science-ore",
    icons = {{icon = "__leighzerscienceores__/graphics/icons/ore.png", tint= leighzermods.leighzerscienceores.tints.production}},
    icon_size = 32,            
    subgroup = "raw-resource",
    order = "a-b-a",
    stack_size = 50,
  },
  {
    type = "item",
    name = "utility-science-ore",
    icons = {{icon = "__leighzerscienceores__/graphics/icons/ore.png", tint= leighzermods.leighzerscienceores.tints.utility}},
    icon_size = 32,            
    subgroup = "raw-resource",
    order = "a-b-a",
    stack_size = 50,
  },
  {
    type = "item",
    name = "space-science-ore",
    icons = {{icon = "__leighzerscienceores__/graphics/icons/ore.png", tint= leighzermods.leighzerscienceores.tints.science}},
    icon_size = 32,            
    subgroup = "raw-resource",
    order = "a-b-a",
    stack_size = 50,
  },    
                  
})