data:extend(
{    
  {--prototype for object that gets stored in inventory when ore is mined
    type = "item",
    name = "automation-science-ore",
    icons = {{icon = "__leighzerscienceores__/graphics/icons/automation-science-ore.png"}},
    icon_size = 32,            
    subgroup = "raw-resource",
    order = "a-b-a",
    stack_size = 50,
  },
  {
    type = "item",
    name = "logistic-science-ore",
    icons = {{icon = "__leighzerscienceores__/graphics/icons/logistic-science-ore.png"}},
    icon_size = 32,            
    subgroup = "raw-resource",
    order = "a-b-b",
    stack_size = 50,
  },
  {
    type = "item",
    name = "military-science-ore",
    icons = {{icon = "__leighzerscienceores__/graphics/icons/military-science-ore.png"}},
    icon_size = 32,            
    subgroup = "raw-resource",
    order = "a-b-c",
    stack_size = 50,
  },
  {
    type = "item",
    name = "chemical-science-ore",
    icons = {{icon = "__leighzerscienceores__/graphics/icons/chemical-science-ore.png"}},
    icon_size = 32,            
    subgroup = "raw-resource",
    order = "a-b-d",
    stack_size = 50,
  },
  {
    type = "item",
    name = "production-science-ore",
    icons = {{icon = "__leighzerscienceores__/graphics/icons/production-science-ore.png"}},
    icon_size = 32,            
    subgroup = "raw-resource",
    order = "a-b-e",
    stack_size = 50,
  },
  {
    type = "item",
    name = "utility-science-ore",
    icons = {{icon = "__leighzerscienceores__/graphics/icons/utility-science-ore.png"}},
    icon_size = 32,            
    subgroup = "raw-resource",
    order = "a-b-f",
    stack_size = 50,
  },
  {
    type = "item",
    name = "space-science-ore",
    icons = {{icon = "__leighzerscienceores__/graphics/icons/space-science-ore.png"}},
    icon_size = 32,            
    subgroup = "raw-resource",
    order = "a-b-g",
    stack_size = 50,
  },    
                  
})